name: PB2S Conformance
on: [push, pull_request]

jobs:
  conformance:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Start server
        run: python -m uvicorn server.main:app --host 127.0.0.1 --port 8000 &

      - name: Wait for server
        run: |
          for i in {1..30}; do
            curl -sSf http://127.0.0.1:8000/docs >/dev/null && break || sleep 1
          done

      - name: Conformance
        run: python scripts/conformance.py --endpoint http://127.0.0.1:8000/chat
