name: PB2S Conformance
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: uvicorn server.main:app --port 8000 --host 127.0.0.1 &
      - name: Wait for server
        run: |
          for i in {1..20}; do
            curl -sSf http://127.0.0.1:8000/docs >/dev/null && break || sleep 1
          done
      - run: python scripts/conformance.py --endpoint http://127.0.0.1:8000/chat
