name: PB2S Conformance & Acceptance Tests

on:
  push:
    paths:
      - 'specification/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'specification/**'
      - 'scripts/**'

jobs:
  pb2s_ci:
    name: Run Conformance Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate SOT Sections
        run: |
          python scripts/sot_verify.py \
            --spec specification/SPEC-2_Total_Attention_EdgeAI_v0.2.1.1_RELEASE.md \
            --sections 2..10 \
            --schema schemas/pb2s_proof.v2.schema.json

      - name: Start PB2S Planner (local simulation)
        run: |
          python main.py &
          for i in {1..60}; do curl -fsS http://127.0.0.1:8000/openapi.json && break; sleep 1; done

      - name: Run Core Conformance Test
        run: |
          python scripts/conformance.py --endpoint http://127.0.0.1:8000/chat

      - name: Run Acceptance Test Bundle (AT‑1 to AT‑7)
        run: |
          python scripts/at_bus.py
          python scripts/at_determinism.py
          python scripts/at_clarify.py
          python scripts/at_proof_to_action.py
          python scripts/at_retention.py

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pb2s_evidence
          path: docs/challenges/*.json
